use_frameworks!

platform :ios, '10.0'

target 'BGCocoaLumberjack_Example' do
  pod 'BGCocoaLumberjack', :path => '../'

  target 'BGCocoaLumberjack_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
