use_frameworks!

platform :ios, '10.0'

target 'BGURLRouter_Example' do
  pod 'BGURLRouter', :path => '../'

  target 'BGURLRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
