use_frameworks!

platform :ios, '10.0'

target 'BITBaseTabBarController_Example' do
  pod 'BITBaseTabBarController', :path => '../'

  target 'BITBaseTabBarController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
