use_frameworks!

platform :ios, '10.0'

target 'DHModule_Example' do
  pod 'DHModule', :path => '../'

  target 'DHModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'DHModule', :path => '../'
  end
end
